---
title: "BIS 557 Computational Statistics"
author: "Michael J. Kane"
output: md_document
---

## Office Hours

Tuesdays 10:00 AM - 12:00 PM

## Teaching Assistant

Chang Su: c dot su at yale dot edu

Office hours for and sessions run by Chang will be posted based on 
student availability.

## Texts

We will be using a preprint of [_A Computational Approach to Statistical Learning_ by Arnold, Kane, Lewis](https://www.amazon.com/Computational-Approach-Statistical-Learning-Chapman/dp/113804637X?SubscriptionId=AKIAILSHYYTFIVPWUY6Q&tag=duckduckgo-brave-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=113804637X).

## Grading

Your work-product for this class is going to be an R package that includes all of the code, documentation, and write-ups you create for the class. The package will be stored on [Github](https://github.com/). It must be properly documented and include regression testing.

Equal weight will be given to homeworks, a midterm project, and a cumulative final project.

## Objectives

The goal of this class is to develop the skills required to design and implement algorithms for statistical analyses. We will work toward those goals by studying some of the most successful statistical procedures currently in use and implementing them in R and Python. To do well in this class you will need to be able to prove characteristics of a model, create algorithms for fitting models, and write R and Python code to implement those algorithms.

## Assignments

Assignments will be given about every two weeks and will cover material concurrent with the lectures. Late assignments late will be penalized heavily. 

## Plagiarism

Assignments will require you to write R and Python code and create write-ups. You may use code you find elsewhere as a starting point. However, you must reference where the code was found, and you must delineate which code is yours or how you extended the copied code to fulfill the assignment.

Periodically, I will test the similarity between your package and other students' packages. If code, documentation, or a write-ups are plagiarized, then the person with the earlier checkin will be awarded full credit and others will receive no credit.

## Topics

- Reproducibility and Open Statistics
    - Writing R packages
    - Using source-code repositories
    - Regression testing
    - Continuous integration
- Linear Models
    - Ordinary Least Squares
    - Solving least squares with the pseudo-inverse
    - Solving linear models with orthogonal projections
    - The relationship between numerical and statistical error
    - Tikhonov Regularization
- Python for Data Science
    - Using R to learn python
    - Writing software systems
    - Python packages
- Generalized Linear Models
    - Logisitic regression
    - Exponential families
    - Iteratively reweighted least squares
- Penalized regression models
    - Variable selection
    - Convex optimization and the elastic net
    - Active set screening with KKT
- Deep learning
    - Dense neural network architecture
    - Stochastic gradient descent
    - Backward propogation
    - Convolutional neural networks
- Dimension reduction (if time allows)
    - Kernel functions
    - Kernel PCA
    - Spectral clustering
    - t-Distributed stochastic neighbor embedding (t-SNE) 
    - Autoencoders
- Linear Smoothers (if time allows)
    - Basis expansion
    - Kernel regression
    - Splines
